PythonTab = "(//*[@id='link']//li)[2]"
PythonNotesJavaTPoint = "(//*[@id='city']//p)[5]"
Code1 = "(//*[@class='dp-j'])[5]"
Code2 = "(//*[@class='dp-j'])[6]"
Code3 = "(//*[@class='dp-j'])[11]"
PythonNotesTutorialsPoint_1 = "(//*[@class='list'])[2]"
tp_operators = "(//*[@class='toc chapters']//li)[8]"
Code1_tp = "//*[@class='prettyprint notranslate prettyprinted']"
tp_functions = "(//*[@class='toc chapters']//li)[16]"
Code2_tp = "(//*[@class='prettyprint notranslate prettyprinted'])[2]"
Code3_tp = "(//*[@class='prettyprint notranslate prettyprinted'])[3]"

# GeeksForGeeks Xpaths
AuthenticationButton = "//*[@class='header-main__signup login-modal-btn']"
SignInButton = "//*[@class='btn btn-green signin-button']"
UserProfileId = "//*[@id='userProfileId']//img"
UserInformation = "//*[@class='gfg-icon gfg-icon_user']"
MyProfile = "(//*[@class='mdl-navigation__link ']//i)[1]"
InstitutionName = "(//*[@class='mdl-grid']//*[@class='mdl-cell mdl-cell--9-col mdl-cell--12-col-phone textBold'])[1]"
Name = "//*[@class='mdl-grid']//*[@class='mdl-cell mdl-cell--9-col mdl-cell--12-col-phone textBold medText']"
EmailId = "(//*[@class='mdl-grid']//*[@class='mdl-cell mdl-cell--9-col mdl-cell--12-col-phone textBold'])[2]"
Courses = "(//*[@class='mdl-cell mdl-cell--9-col mdl-cell--12-col-phone textBold'])[2]"
Practice = "(//*[@class='mdl-navigation__link '])[1]"
FeedSection = "(//*[@class='mdl-navigation__link '])[2]"
InterestSection = "(//*[@class='mdl-navigation__link '])[3]"
GfgBackIcon = "//*[@class='gfg-logo-ul']//li"
Tutorials = "(//*[@class='header-main__list-item'])[1]"
AlgorithmPage = "(//*[@class='mega-dropdown__list-item'])[1]"
AlgorithmAnalysisPage = "(//*[@class='mega-dropdown__list-item'])[1]"
AsymptoticNotationPage = "(//*[@class='mega-dropdown__list-item'])[1]"
TitleOfPage = "(//*[@class='title'])[1]"
TextAsymptoticNotation = "(//*[@class='text'])[1]"
CoursesPage = "(//*[@class='header-main__list-item'])[3]"
GetHiredPage = "(//*[@class='header-main__list-item'])[3]"
CrossPage = "//*[@class='gsc-results-close-btn gsc-results-close-btn-visible']"
BackButton = "//*[@class='_logo']"
Logo = "//*[@class='_logo']"

